// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8iUoVtZvM6D_sfOZi44N4kILKfnnwnW0',
    appId: '1:788121705937:web:e1b6dcb18eee7de43c14f0',
    messagingSenderId: '788121705937',
    projectId: 'smarthome-e9805',
    authDomain: 'smarthome-e9805.firebaseapp.com',
    storageBucket: 'smarthome-e9805.appspot.com',
    measurementId: 'G-4K0PR7HDLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1oe6gtF0VBwNiybyEIFbqCLaf_UVEv8',
    appId: '1:788121705937:android:7c58746727e73a7d3c14f0',
    messagingSenderId: '788121705937',
    projectId: 'smarthome-e9805',
    storageBucket: 'smarthome-e9805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIEAZ2ZzEfYUuAVN5SwXy7iBidr-TqhDo',
    appId: '1:788121705937:ios:760e599dff437d403c14f0',
    messagingSenderId: '788121705937',
    projectId: 'smarthome-e9805',
    storageBucket: 'smarthome-e9805.appspot.com',
    iosClientId: '788121705937-7b370ijt511472saucng8047ng7mir89.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIEAZ2ZzEfYUuAVN5SwXy7iBidr-TqhDo',
    appId: '1:788121705937:ios:760e599dff437d403c14f0',
    messagingSenderId: '788121705937',
    projectId: 'smarthome-e9805',
    storageBucket: 'smarthome-e9805.appspot.com',
    iosClientId: '788121705937-7b370ijt511472saucng8047ng7mir89.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarthome',
  );
}
